language:
  - cpp

matrix:
  include:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew install polyml imagemagick ; fi

before_script:
  - ./repoint install
  - ./obtain-data.sh

script:
  - make
  - ( cd with-tiny-dnn ; make )
  - ./evaluate.sh
  - ./evaluate.sh with-tiny-dnn/with-tiny-dnn

